name: GERAR REPO

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Python
        uses: actions/setup-python@v2  # Ação para configurar a versão do Python
        with:
          python-version: 3.9  # Especifique a versão do Python que deseja usar

      - name: Instalar requests
        run: |
          pip install requests
  
      - name: Rodar rotina
        run: |
          ls
          python rotina.py
          
      - name: Publicar no repositorio
        run: |
          git clone -b repo https://${{ secrets.GH_TOKEN }}@github.com/zoreu/titanrepo.git original
          cp -r hibrido original
          cp -r leia original
          cp -r matrix original
          cd original
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update epg.xml"
          git push --force origin output          
          
        
